# Generated by Django 3.0.2 on 2020-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ono', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('destination', models.CharField(choices=[('Panbazaar', 'Panbazaar'), ('Jalukbari', 'Jalukbari'), ('Airport', 'Airport'), ('PaltanBazaar', 'PaltanBazaar'), ('GS Road', 'GS Road'), ('Maligaon', 'Maligaon')], default='Airport', max_length=50)),
                ('car_type', models.CharField(choices=[('Maruti Alto', 'Maruti Alto'), ('Swift Dzire', 'Swift Dzire'), ('Innova', 'Innova'), ('Indica', 'Indica'), ('Carpool', 'Carpool')], default='Maruti Alto', max_length=50)),
            ],
        ),
    ]
